# Generated by Django 4.1 on 2023-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.CharField(
                choices=[
                    ("CS299", "CS299"),
                    ("CS399", "CS399"),
                    ("EEE299", "EEE299"),
                    ("EEE399", "EEE399"),
                    ("ME299", "ME299"),
                    ("ME399", "ME399"),
                    ("IE299", "IE299"),
                    ("IE399", "IE399"),
                ],
                max_length=6,
                null=True,
            ),
        ),
    ]
