# Generated by Django 4.1 on 2023-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_student_assigned_instructor_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="assigned_instructor",),
        migrations.AddField(
            model_name="instructor",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                null=True,
                related_name="instructor_of_student",
                to="users.student",
            ),
        ),
    ]
