# Generated by Django 4.1.7 on 2023-05-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_instructor_students_student_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='students',
        ),
    ]
