# Generated by Django 4.1.7 on 2023-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_student_course_remove_student_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
