# Generated by Django 4.1 on 2023-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="departments",
            field=models.ManyToManyField(blank=True, to="users.engineeringdepartment"),
        ),
    ]
