# Generated by Django 4.1.7 on 2023-05-25 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyapprovalvalidationapplication',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
    ]
