# Generated by Django 4.1.7 on 2023-05-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrelateddemand',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='company.company'),
        ),
        migrations.AlterField(
            model_name='companyrelateddemand',
            name='file',
            field=models.FileField(null=True, upload_to='company-related-demands'),
        ),
    ]
