# Generated by Django 4.1.7 on 2023-05-25 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyapprovalvalidationapplication_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationbystudent',
            name='grade',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
