# Generated by Django 4.1.7 on 2023-05-25 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('company', '0004_alter_evaluationbystudent_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='companyrequest',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.student'),
        ),
    ]
