# Generated by Django 4.1.7 on 2023-05-03 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='superuser', to=settings.AUTH_USER_MODEL)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(related_name='superusers', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='superuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Superuser',
                'verbose_name_plural': 'Superusers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='student', to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(choices=[('CS', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('bilkent_id', models.IntegerField(unique=True)),
                ('groups', models.ManyToManyField(related_name='students', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='student_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='instructor', to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(choices=[('CS', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('groups', models.ManyToManyField(related_name='instructors', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='instructor_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
            },
        ),
        migrations.CreateModel(
            name='DepartmentSecretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='dep_secretary', to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(choices=[('CS', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(related_name='dep_secretaries', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='dep_secretary_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Department Secretary',
                'verbose_name_plural': 'Department Secretaries',
            },
        ),
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='dean', to=settings.AUTH_USER_MODEL)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(related_name='deans', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='dean_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Dean',
                'verbose_name_plural': 'Deans',
            },
        ),
    ]
