# Generated by Django 4.1.7 on 2023-05-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPERUSER', 'Superuser'), ('STUDENT', 'Student'), ('DEAN', 'Dean'), ('CHAIR', 'Chair'), ('INSTRUCTOR', 'Instructor'), ('DEPARTMENT_SECRETARY', 'Department Secretary')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SuperUser',
        ),
    ]
