# Generated by Django 4.1.7 on 2023-05-03 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_remove_student_bilkent_id_alter_dean_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dean',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering')], default='EEE', max_length=3),
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='chair', to=settings.AUTH_USER_MODEL)),
                ('is_staff', models.BooleanField(default=True)),
                ('department', models.CharField(choices=[('CS', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('groups', models.ManyToManyField(related_name='chairs', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='chair_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Chair',
                'verbose_name_plural': 'Chairs',
            },
        ),
    ]
