# Generated by Django 4.1.7 on 2023-05-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dean_department_chair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dean',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering')], max_length=3),
        ),
    ]
