# Generated by Django 4.1.7 on 2023-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0003_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('CS299', 'CS299'), ('CS399', 'CS399'), ('EEE299', 'EEE299'), ('EEE399', 'EEE399'), ('ME299', 'ME299'), ('ME399', 'ME399'), ('IE299', 'IE299'), ('IE399', 'IE399')], max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='%(class)spermissions', to='auth.permission'),
        ),
    ]
