# Generated by Django 4.1.7 on 2023-05-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dean_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='dean',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='departmentsecretary',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='superuser',
            name='user_ptr',
        ),
    ]
