# Generated by Django 4.1 on 2023-05-07 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('chair', '0001_initial'),
        ('student', '0001_initial'),
        ('instructor', '0001_initial'),
        ('departmentSecretary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dean',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(choices=[('CS', 'Computer Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IE', 'Industrial Engineering'), ('ME', 'Mechanical Engineering')], max_length=3)),
                ('chairs', models.ManyToManyField(blank=True, editable=False, related_name='dean_of_chairs', to='chair.chair')),
                ('instructors', models.ManyToManyField(blank=True, editable=False, related_name='dean_of_instructors', to='instructor.instructor')),
                ('secretaries', models.ManyToManyField(blank=True, editable=False, related_name='dean_of_secretaries', to='departmentSecretary.departmentsecretary')),
                ('students', models.ManyToManyField(blank=True, editable=False, related_name='dean_of_students', to='student.student')),
            ],
            options={
                'verbose_name': 'Dean',
                'verbose_name_plural': 'Deans',
            },
            bases=('main.user',),
        ),
    ]
