# Generated by Django 4.1.7 on 2023-05-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_instructor_students_student_students'),
        ('company', '0003_alter_companyrelateddemand_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('submission_date', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ConfidentialCompanyForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.form')),
            ],
            bases=('reports.form',),
        ),
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.form')),
                ('grade', models.IntegerField(null=True)),
            ],
            bases=('reports.form',),
        ),
        migrations.CreateModel(
            name='GradingForm',
            fields=[
                ('form_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.form')),
                ('due_date', models.DateTimeField(null=True)),
            ],
            bases=('reports.form',),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.task')),
            ],
            bases=('reports.task',),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='company.company')),
                ('company_approval', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='company.companyapprovalvalidationapplication')),
                ('company_evaluation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='company.evaluationbystudent')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship', to='users.course')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='users.student')),
                ('confidential_company_form', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='reports.confidentialcompanyform')),
                ('evaluation_form', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='reports.evaluationform')),
                ('grading_form', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='reports.gradingform')),
            ],
        ),
        migrations.AddField(
            model_name='gradingform',
            name='student_submission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_form', to='reports.submission'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.task')),
                ('submission_field', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reports.submission')),
            ],
            bases=('reports.task',),
        ),
    ]
