# Generated by Django 4.1.7 on 2023-05-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship', to='users.course'),
        ),
        migrations.AddField(
            model_name='internship',
            name='instructor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internship', to='users.student'),
        ),
        migrations.AddField(
            model_name='internship',
            name='work_and_report_evaluation_form',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship', to='reports.workandreportevaluation'),
        ),
        migrations.AddField(
            model_name='internship',
            name='student_report',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship', to='reports.submission'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submission_field',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reports.submission'),
        ),
    ]
