# Generated by Django 4.1 on 2023-05-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workandreportevaluation",
            name="total_work_grade",
            field=models.IntegerField(null=True),
        ),
    ]
