# Generated by Django 4.1.7 on 2023-05-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='due_date',
            field=models.DateField(),
        ),
    ]
