# Generated by Django 4.1.7 on 2023-05-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0003_alter_workandreportevaluation_total_work_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtensionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_date', models.DateTimeField()),
                ('submission',
                 models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extensions',
                                      to='reports.submission')),
            ],
        ),
    ]
