# Generated by Django 4.1.7 on 2023-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_internship_instructor_alter_internship_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='is_work_related',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='supervisor_background',
            field=models.BooleanField(null=True),
        ),
    ]
