# Generated by Django 4.1.7 on 2023-05-27 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reports', '0004_extensionform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtensionForm',
            new_name='ExtensionRequest',
        ),
    ]
