# Generated by Django 4.1.7 on 2023-05-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_submission_due_date_alter_task_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('SA', 'Satisfactory'), ('RR', 'Revision Required'), ('UN', 'Unsatisfactory'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
    ]
