# Generated by Django 4.1.7 on 2023-05-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_extensionform_extensionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionrequest',
            name='submission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='reports.submission'),
        ),
    ]
